# Generated by Django 5.2.13 on 2026-05-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='is_teacher',
            new_name='teacher',
        ),
    ]
