# Generated by Django 5.2.13 on 2026-06-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_teacher_customeruser_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='teacher',
            field=models.BooleanField(default=False, verbose_name='Вы хотите иметь возможность создавать курсы?'),
        ),
    ]
