# Generated by Django 5.2.13 on 2026-05-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_course',
            name='answers',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Test_answers',
        ),
    ]
