# Generated by Django 5.2.13 on 2026-05-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_test_course_answers_delete_test_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_slides',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test_course',
            name='slide',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='text_course',
            name='slide',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video_course',
            name='slide',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
