# Generated by Django 5.2.13 on 2026-05-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_max_slides_test_course_slide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curent_slides',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
