# Generated by Django 5.2.13 on 2026-05-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_test_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_course',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
