# Generated by Django 5.2.13 on 2026-05-30 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_test_course_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_answers',
            name='test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.test_course', verbose_name='Название теста'),
        ),
    ]
