# Generated by Django 5.2.13 on 2026-05-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_test_answers_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='max_slides',
        ),
        migrations.AddField(
            model_name='course',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
