# Generated by Django 5.2.13 on 2026-05-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_max_slides_course_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_course',
            name='answers',
        ),
    ]
