# Generated by Django 5.2.13 on 2026-06-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_test_course_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
