# Generated by Django 5.2.13 on 2026-06-02 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_answers',
            name='course',
        ),
        migrations.CreateModel(
            name='Practice_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('complaints', models.TextField()),
                ('age', models.PositiveBigIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('diagnosis', models.TextField()),
                ('slide', models.PositiveBigIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_pactices', to='courses.course', verbose_name='Название курса')),
            ],
        ),
        migrations.CreateModel(
            name='Practice_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.TextField(verbose_name='Тесты')),
                ('treatment', models.TextField(verbose_name='Лечние')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('pactice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.practice_course', verbose_name='Название задания')),
            ],
        ),
    ]
