# Generated by Django 5.2.13 on 2026-06-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_test_answers_course_practice_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice_answers',
            old_name='pactice',
            new_name='practice',
        ),
    ]
