# Generated by Django 5.2.13 on 2026-06-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_rename_pactice_practice_answers_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category_name',
            field=models.CharField(default='Massage', max_length=100),
        ),
    ]
