# Generated by Django 5.2.13 on 2026-06-07 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='extra_teachers',
            field=models.ManyToManyField(blank=True, related_name='extra_courses', to=settings.AUTH_USER_MODEL, verbose_name='Дополнительные учителя курса'),
        ),
    ]
