# Generated by Django 5.2.13 on 2026-06-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_practice_answers_results_test_answers_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_answers',
            name='commentary',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
