# Generated by Django 5.2.13 on 2026-06-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_practice_answers_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice_course',
            name='gender',
            field=models.CharField(choices=[('men', 'Мужчина'), ('women', 'Женщина')], default='men', max_length=10),
        ),
    ]
