# Generated by Django 5.2.13 on 2026-06-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_remove_course_category_name_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category_id',
            new_name='category',
        ),
    ]
