# Generated by Django 5.2.13 on 2026-06-20 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_student_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_answers',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_practice_answers', to='courses.course', verbose_name='Название курса'),
        ),
        migrations.AddField(
            model_name='test_answers',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_test_answers', to='courses.course', verbose_name='Название курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_mock',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_mock_answers', to='courses.course', verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='practice_course',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_pactices', to='courses.course', verbose_name='Название курса'),
        ),
    ]
